name: Integration Tests

on:
  workflow_call: # Allows this workflow to be called from another workflow
  push:
    branches: 
      - main

jobs:
  end_to_end_tests:
    runs-on: ubuntu-latest
    env:
        E2E_SECRET: ${{ secrets.E2E_SECRET }}
        OMNIBUS_ALLOWLIST_KEYS: ${{ secrets.OMNIBUS_ALLOWLIST_KEYS }}

    steps:
      - uses: actions/checkout@v3

      - name: Run end-to-end tests (Default Config)
        run: make run-e2e-tests
